apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo
  labels:
    app: odoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: jhoelfloress/odoo:17  # Cambia a la imagen que prefieras o a una personalizada
        ports:
        - containerPort: 8069
        env:
        - name: HOST
          value: "db"
        - name: USER
          value: "odoo"
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: password
        volumeMounts:
        - mountPath: /var/lib/odoo
          name: odoo-web-data
        resources:
          requests:
            memory: "1Gi"   # Solicita 1 GB de memoria
            cpu: "500m"     # Solicita 500 milicores de CPU
          limits:
            memory: "2Gi"   # Límite de 2 GB de memoria
            cpu: "1"
      volumes:
      - name: odoo-web-data
        emptyDir: {}
