apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15  # Cambia la versión si es necesario
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "odoo"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: odoo-db-secret
              key: password
        - name: POSTGRES_DB
          value: "postgres"
